name: Build and release docker image
on:
  workflow_dispatch:
  push:
    tags:
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: pnpm/action-setup@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build with VitePress
        run: |
          pnpm docs:build
          touch docs/.vitepress/dist/.nojekyll
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t fmhy-website:latest .
          docker save -o fmhy-website.tar fmhy-website:latest
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          artifacts: "fmhy-website.tar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
